"""Render exported schedules as APScheduler ``add_job(...)`` calls.

Output is a Python script the operator can drop into their
APScheduler bootstrap. Each schedule emits one ``scheduler.add_job``
call with the right trigger args.

The operator owns the ``BaseScheduler`` instance + the executor
configuration. The script provides ``register_schedules(scheduler)``
so the operator can wire it as part of their own startup hook.
"""

from __future__ import annotations

import json
from collections.abc import Iterable

from z4j_scheduler.exporters._client import ExportedSchedule, py_repr


def render(schedules: Iterable[ExportedSchedule]) -> str:
    """Return a Python source string for APScheduler."""
    schedules = list(schedules)
    lines: list[str] = [
        "# Generated by `z4j-scheduler export --to apscheduler`. Do not edit by hand.",
        "# Pass your existing scheduler to register_schedules().",
        "",
        "from datetime import datetime",
        "",
        "",
        "def register_schedules(scheduler):",
        "    \"\"\"Apply z4j-managed schedules to an APScheduler Scheduler.\"\"\"",
    ]
    if not schedules:
        lines.append("    return  # no z4j schedules to migrate")
        return "\n".join(lines) + "\n"

    for sched in schedules:
        lines.extend(_render_one(sched))
    return "\n".join(lines) + "\n"


def _render_one(sched: ExportedSchedule) -> list[str]:
    # ``py_repr`` (not json.dumps) so booleans / None inside args
    # or kwargs render as Python literals (True/False/None) rather
    # than JSON literals (true/false/null), which would NameError at
    # exec time when an operator pastes the script into their
    # startup. Same fix applied to celery + rq exporters.
    args_repr = py_repr(list(sched.args))
    kwargs_repr = py_repr(dict(sched.kwargs))
    enabled_kw = ", paused=True" if not sched.is_enabled else ""

    if sched.kind == "cron":
        cron_kwargs = _cron_to_kwargs(sched.expression)
        return [
            f"    scheduler.add_job(",
            f"        {json.dumps(sched.task_name)},",
            f"        \"cron\",",
            *[
                f"        {key}={json.dumps(value)},"
                for key, value in cron_kwargs.items()
            ],
            f"        timezone={json.dumps(sched.timezone)},",
            f"        id={json.dumps(sched.id)},",
            f"        name={json.dumps(sched.name)},",
            f"        args={args_repr},",
            f"        kwargs={kwargs_repr},",
            f"        replace_existing=True{enabled_kw},",
            f"    )",
        ]
    if sched.kind == "interval":
        from z4j_scheduler.exporters.celery import _interval_to_seconds

        seconds = _interval_to_seconds(sched.expression)
        return [
            f"    scheduler.add_job(",
            f"        {json.dumps(sched.task_name)},",
            f"        \"interval\",",
            f"        seconds={seconds},",
            f"        id={json.dumps(sched.id)},",
            f"        name={json.dumps(sched.name)},",
            f"        args={args_repr},",
            f"        kwargs={kwargs_repr},",
            f"        replace_existing=True{enabled_kw},",
            f"    )",
        ]
    if sched.kind == "one_shot":
        return [
            f"    scheduler.add_job(",
            f"        {json.dumps(sched.task_name)},",
            f"        \"date\",",
            f"        run_date=datetime.fromisoformat({json.dumps(sched.expression)}),",
            f"        id={json.dumps(sched.id)},",
            f"        name={json.dumps(sched.name)},",
            f"        args={args_repr},",
            f"        kwargs={kwargs_repr},",
            f"        replace_existing=True{enabled_kw},",
            f"    )",
        ]
    return [f"    # unknown kind {sched.kind!r} for schedule {sched.name!r}"]


def _cron_to_kwargs(expression: str) -> dict[str, str]:
    """Map a 5-field cron string to APScheduler keyword args.

    APScheduler's ``cron`` trigger uses named fields rather than a
    crontab string; we split + label.
    """
    parts = expression.split()
    if len(parts) != 5:
        return {"minute": "*"}
    minute, hour, day, month, dow = parts
    return {
        "minute": minute,
        "hour": hour,
        "day": day,
        "month": month,
        "day_of_week": dow,
    }


__all__ = ["render"]
