"""Render exported schedules as an arq ``cron_jobs`` Python module.

Output is a Python module the operator drops into their arq
``WorkerSettings``. Each schedule renders one ``cron(...)`` call.
The operator wires it::

    from .z4j_arq_schedules import build_cron_jobs

    class WorkerSettings:
        functions = [send_email, generate_report]
        cron_jobs = build_cron_jobs([send_email, generate_report])

The operator passes their function objects in; we look up by name.

Limitations:

- Only ``kind="cron"`` is supported. Interval / one_shot / solar
  schedules emit a comment + skip; the operator keeps those on
  z4j-scheduler.
- arq doesn't have a per-cron-job queue concept (the queue is on
  WorkerSettings); the schedule's ``queue`` field renders as a
  comment annotation only.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable

from z4j_scheduler.exporters._client import ExportedSchedule

_CRON_FIELD_CHARS = re.compile(r"^[\d*/,\-]+$")


def _is_safe_cron_expression(expression: str) -> bool:
    fields = expression.strip().split()
    if len(fields) not in (5, 6):
        return False
    return all(_CRON_FIELD_CHARS.match(f) for f in fields)


def render(schedules: Iterable[ExportedSchedule]) -> str:
    schedules = list(schedules)
    lines: list[str] = [
        "# Generated by `z4j-scheduler export --to arq`. Do not edit by hand.",
        "# Wire by importing build_cron_jobs into your WorkerSettings",
        "# and passing the function objects you want resolved by name.",
        "",
        "from arq import cron",
        "",
        "",
        "def build_cron_jobs(functions):",
        "    \"\"\"Return a list of arq.cron.CronJob from z4j schedules.",
        "",
        "    ``functions`` is the same list you pass to",
        "    ``WorkerSettings.functions``. We resolve task_name to a",
        "    callable by ``__name__`` lookup.",
        "    \"\"\"",
        "    by_name = {",
        "        getattr(fn, '__name__', repr(fn)): fn for fn in functions",
        "    }",
        "    jobs = []",
    ]
    if not schedules:
        lines.append("    return jobs  # no z4j schedules to migrate")
        return "\n".join(lines) + "\n"

    rendered_any = False
    for sched in schedules:
        rendered = _render_one(sched)
        if rendered:
            lines.extend(rendered)
            rendered_any = True

    lines.append("    return jobs")
    if not rendered_any:
        # No actual cron entries; the prelude already added 'jobs = []'.
        pass
    return "\n".join(lines) + "\n"


def _render_one(sched: ExportedSchedule) -> list[str]:
    safe_name = re.sub(r"[\r\n\x00]+", " ", sched.name)[:200]
    safe_task_name = re.sub(r"[\r\n\x00]+", " ", sched.task_name)[:200]
    safe_expr = re.sub(r"[\r\n\x00]+", " ", sched.expression)[:200]

    if not sched.is_enabled:
        return [
            f"    # DISABLED in z4j: {safe_name} - {safe_task_name}",
            "",
        ]

    if sched.kind != "cron":
        return [
            f"    # {safe_name}: kind={sched.kind!r} not supported by arq cron;",
            f"    # keep on z4j-scheduler. expression={safe_expr!r}",
            "",
        ]

    if not _is_safe_cron_expression(sched.expression):
        return [
            f"    # {safe_name}: REFUSED cron expression {safe_expr!r}",
            "",
        ]

    parts = sched.expression.strip().split()
    if len(parts) == 6:
        # 6-field z4j cron has seconds; arq cron has its own
        # second field but accepts int/set. Drop seconds field
        # for simplicity; operator can re-add via WorkerSettings.
        parts = parts[:5]

    minute, hour, day, month, dow = parts

    queue_note = (
        f"    # original queue: {json.dumps(sched.queue)}\n"
        if sched.queue else ""
    )
    # arq's task_name is the function's __name__, not a dotted
    # module path. Strip the module prefix.
    fn_name = safe_task_name.rsplit(".", 1)[-1]
    return [
        (
            f"{queue_note}    if {json.dumps(fn_name)} in by_name:"
        ),
        (
            f"        jobs.append(cron("
            f"by_name[{json.dumps(fn_name)}], "
            f"name={json.dumps(safe_name)}, "
            f"minute={_arq_field(minute)}, "
            f"hour={_arq_field(hour)}, "
            f"day={_arq_field(day)}, "
            f"month={_arq_field(month)}, "
            f"weekday={_arq_field(dow)}"
            f"))"
        ),
        "",
    ]


def _arq_field(value: str) -> str:
    """Render a 5-field-cron field as an arq cron() argument value.

    arq accepts ``None`` (any), ``int`` (single value), ``set[int]``
    (multiple). We map: ``"*"`` -> ``None``; integer string -> int;
    comma list -> set.
    """
    if value == "*":
        return "None"
    if "," in value:
        try:
            return "{" + ", ".join(str(int(v)) for v in value.split(",")) + "}"
        except ValueError:
            # Fall through to string passthrough below.
            pass
    try:
        return str(int(value))
    except ValueError:
        return json.dumps(value)


__all__ = ["render"]
