"""Render exported schedules as a celery-beat ``beat_schedule`` dict.

Output is a Python module the operator can drop into their Celery
app config:

    # generated by `z4j-scheduler export --to celery ...`
    from celery.schedules import crontab
    from datetime import timedelta

    beat_schedule = {
        "every-hour": {
            "task": "myapp.tasks.heartbeat",
            "schedule": crontab(minute="0"),
            "args": [],
            "kwargs": {},
            "options": {"queue": "default"},
        },
        ...
    }

The operator wires this into ``app.conf.beat_schedule`` per the
celery docs.

Cron expressions are emitted as ``crontab(...)`` calls with
keyword fields the operator can read at a glance. Interval
expressions emit ``timedelta(seconds=N)``. One-shot schedules emit
a ``crontab(...)`` for a fixed minute/hour - celery-beat doesn't
have a native one-shot trigger, so we render with a comment
warning the operator to remove the row after it fires.
"""

from __future__ import annotations

import json
import math
import re
from collections.abc import Iterable

from z4j_scheduler.exporters._client import ExportedSchedule, py_repr
from z4j_scheduler.tick.solar import VALID_EVENTS as _SOLAR_VALID_EVENTS

# Mirror the cron exporter's strict
# whitelist for cron field characters. The celery exporter renders a
# Python file the operator's celery worker imports - any expression
# field that escapes through here lands in their interpreter, so we
# refuse to render anything we can't prove safe.
_CRON_FIELD_CHARS = re.compile(r"^[\d*/,\-]+$")

# Acceptable interval expression shape: "<digits><unit?>". Strict
# allow-list rather than letting ``int(expression[:-1])`` parse
# "0xff" / "1_000_000" / "infinity".
_INTERVAL_PATTERN = re.compile(r"^\s*(\d{1,9})\s*(ms|s|m|h|d)?\s*$")


def render(schedules: Iterable[ExportedSchedule]) -> str:
    """Return a Python source string for celery-beat config."""
    schedules = list(schedules)
    needs_solar = any(s.kind == "solar" for s in schedules)
    lines: list[str] = [
        "# Generated by `z4j-scheduler export --to celery`. Do not edit by hand.",
        "# Drop into your Celery app config as ``app.conf.beat_schedule``.",
        "",
        "from celery.schedules import crontab"
        + (", solar" if needs_solar else ""),
        "from datetime import timedelta",
        "",
        "beat_schedule = {",
    ]
    for sched in schedules:
        lines.extend(_render_one(sched))
    lines.append("}")
    return "\n".join(lines) + "\n"


def _render_one(sched: ExportedSchedule) -> list[str]:
    schedule_expr = _render_schedule_expr(sched)
    options = {}
    if sched.queue:
        options["queue"] = sched.queue
    options_repr = (
        f"        \"options\": {py_repr(options)},\n" if options else ""
    )
    enabled_marker = (
        ""
        if sched.is_enabled
        else "    # NOTE: disabled in z4j; remove this entry to keep it off.\n"
    )
    one_shot_warning = (
        "    # NOTE: original kind was 'one_shot'; celery-beat has no\n"
        "    # native one-shot trigger. This entry will fire repeatedly\n"
        "    # until removed.\n"
        if sched.kind in ("clocked", "one_shot")
        else ""
    )
    # 6-field z4j cron carries a seconds-precision field celery
    # can't express. Drop the seconds + warn the operator above
    # the dict entry so they see the loss in the rendered file.
    seconds_warning = ""
    if sched.kind == "cron" and len(sched.expression.split()) == 6:
        seconds_field = sched.expression.split()[5]
        seconds_warning = (
            f"    # NOTE: original z4j cron had a seconds-precision\n"
            f"    # 6th field {seconds_field!r}; celery-beat's crontab()\n"
            f"    # is minute-resolution only, so the seconds component\n"
            f"    # was dropped on export. Run this schedule on z4j-\n"
            f"    # scheduler if seconds matter; otherwise the rendered\n"
            f"    # crontab is the closest celery-beat equivalent.\n"
        )
    body = [
        f"{seconds_warning}{one_shot_warning}{enabled_marker}    {_quoted(sched.name)}: {{",
        f"        \"task\": {_quoted(sched.task_name)},",
        f"        \"schedule\": {schedule_expr},",
        f"        \"args\": {py_repr(list(sched.args))},",
        f"        \"kwargs\": {py_repr(dict(sched.kwargs))},",
        options_repr.rstrip("\n") if options_repr else "",
        "    },",
    ]
    return [line for line in body if line]


def _render_schedule_expr(sched: ExportedSchedule) -> str:
    """Render the celery schedule expression for one schedule.

    Audit fix C1-celery (Apr 2026): every branch refuses to emit
    operator-controlled values that have not passed strict
    validation. A malicious schedule (created via dashboard or
    imported from a hostile source) used to interpolate non-finite
    floats / unsanitized event strings into the rendered Python
    file the operator's celery worker imports. The fix returns a
    ``# REFUSED ...`` comment in place of the call, the
    surrounding entry render handles a comment in the schedule
    field gracefully (celery never sees the entry; operator gets a
    review prompt next to the schedule name).
    """
    if sched.kind == "cron":
        # 6-field expression: drop the trailing seconds field for
        # the celery crontab() call (warning emitted in _render_one).
        parts = sched.expression.split()
        if len(parts) == 6:
            return _render_crontab(" ".join(parts[:5]))
        return _render_crontab(sched.expression)
    if sched.kind == "interval":
        seconds = _interval_to_seconds(sched.expression)
        if seconds is None:
            return (
                f"None  # REFUSED to render interval expression "
                f"{sched.expression!r}"
            )
        return f"timedelta(seconds={seconds})"
    if sched.kind == "solar":
        return _render_solar(sched.expression)
    if sched.kind in ("clocked", "one_shot"):
        # one_shot expression is an ISO timestamp; we degrade to a
        # crontab that fires every minute - the operator removes
        # the row after the intended fire. The warning above
        # explains.
        return "crontab(minute=\"*\")"
    return f"None  # REFUSED unknown kind {sched.kind!r}"


def _render_solar(expression: str) -> str:
    """Render a solar() call with strict validation.

    Audit fix C1-celery (Apr 2026): the pre-fix path interpolated
    ``event`` (operator-controlled) and lat/lon (operator-controlled
    floats accepted via ``float()``) directly into the rendered
    file. ``float()`` accepts ``"inf"``, ``"-inf"``, ``"nan"`` -
    and the un-validated event string would land verbatim in the
    Python module. Hostile schedule with expression
    ``"sunrise:nan:inf"`` produced a celery beat config that
    crashed celery on load (DoS) or silently never fired (covert
    monitoring disable).
    """
    parts = expression.split(":", 2)
    if len(parts) != 3:
        return f"None  # REFUSED unparseable solar expression {expression!r}"
    event, lat, lon = parts
    if event not in _SOLAR_VALID_EVENTS:
        return (
            f"None  # REFUSED solar event {event!r} not in "
            f"{sorted(_SOLAR_VALID_EVENTS)}"
        )
    try:
        lat_f = float(lat)
        lon_f = float(lon)
    except ValueError:
        return f"None  # REFUSED unparseable solar expression {expression!r}"
    if not (math.isfinite(lat_f) and math.isfinite(lon_f)):
        return (
            f"None  # REFUSED non-finite lat/lon in solar expression "
            f"{expression!r}"
        )
    if not (-90.0 <= lat_f <= 90.0 and -180.0 <= lon_f <= 180.0):
        return (
            f"None  # REFUSED out-of-range lat/lon in solar expression "
            f"{expression!r}"
        )
    # ``!r`` on a validated event string emits a Python-safe literal;
    # combined with the allow-list above the rendered call is fully
    # operator-controlled-input-free.
    return f"solar({event!r}, {lat_f!r}, {lon_f!r})"


def _render_crontab(expression: str) -> str:
    """Convert a 5-field cron string to ``crontab(minute=..., hour=...)``.

    Audit fix C1-celery (Apr 2026): every field is validated
    against a strict whitelist before interpolation. The pre-fix
    path passed any string through ``_quoted`` (json.dumps), but
    Python source string literals can carry NL / U+2028 / null
    bytes that survive json escaping but break the rendered file
    (or worse, defeat audit grep). The fix refuses to render any
    field that isn't a-z 0-9 ``*/,-`` form.
    """
    parts = expression.split()
    if len(parts) != 5:
        return (
            f"None  # REFUSED cron expression {expression!r}: "
            f"expected 5 fields, got {len(parts)}"
        )
    if not all(_CRON_FIELD_CHARS.match(field) for field in parts):
        return (
            f"None  # REFUSED cron expression {expression!r}: "
            f"unsafe characters in one or more fields"
        )
    minute, hour, day, month, dow = parts
    args = [
        f"minute={_quoted(minute)}",
        f"hour={_quoted(hour)}",
        f"day_of_month={_quoted(day)}",
        f"month_of_year={_quoted(month)}",
        f"day_of_week={_quoted(dow)}",
    ]
    return f"crontab({', '.join(args)})"


def _interval_to_seconds(expression: str) -> int | None:
    """Parse ``"30s"``/``"5m"``/``"2h"``/``"1d"`` to seconds.

    Audit fix C1-celery (Apr 2026): returns ``None`` on any
    unparseable input. The pre-fix path used ``int(expression[:-1])``
    which accepts strings ``int()`` accepts beyond plain digits
    (underscored literals, leading ``+``/``-``). Strict regex.
    """
    match = _INTERVAL_PATTERN.match(expression)
    if not match:
        return None
    n = int(match.group(1))
    unit = match.group(2) or "s"
    if unit == "ms":
        return max(1, n // 1000)
    if unit == "s":
        return n
    if unit == "m":
        return n * 60
    if unit == "h":
        return n * 3600
    if unit == "d":
        return n * 86400
    return None  # unreachable per regex but keeps the type-checker honest


def _quoted(s: str) -> str:
    """JSON-encode for safe single-line embedding in Python source."""
    return json.dumps(s)


__all__ = ["render"]
