"""Render exported schedules as a huey periodic-task module.

Output is a Python module the operator can import from their
existing huey configuration. Each schedule emits one
``@huey.periodic_task(crontab(...))`` decorator. The operator wires
it up with::

    from huey import RedisHuey, crontab
    from .z4j_huey_schedules import register_schedules

    huey = RedisHuey("my-app")
    register_schedules(huey)  # registers every z4j-managed schedule

Limitations:

- Huey only supports ``kind="cron"`` natively. Interval / one_shot /
  solar schedules emit a comment + skip; the operator keeps those
  on z4j-scheduler.
- Huey doesn't have a per-task queue concept (a Huey instance IS
  the queue). The schedule's ``queue`` field is rendered as a
  comment annotation only.

The rendered module is `# noqa`-friendly so operator linters
(`ruff`, `pylint`) don't complain about the auto-generated style.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable

from z4j_scheduler.exporters._client import ExportedSchedule

# Same conservative whitelist the cron exporter uses (Apr 2026
# audit fix). Refuses DOW letter aliases - operators with those
# can pre-convert on the brain side.
_CRON_FIELD_CHARS = re.compile(r"^[\d*/,\-]+$")


def _is_safe_cron_expression(expression: str) -> bool:
    fields = expression.strip().split()
    if len(fields) not in (5, 6):
        return False
    return all(_CRON_FIELD_CHARS.match(f) for f in fields)


def render(schedules: Iterable[ExportedSchedule]) -> str:
    """Return a Python source string for huey periodic tasks."""
    schedules = list(schedules)
    lines: list[str] = [
        "# Generated by `z4j-scheduler export --to huey`. Do not edit by hand.",
        "# Wire by importing this module from your huey app and calling",
        "# register_schedules(huey).",
        "",
        "from huey import crontab",
        "",
        "",
        "def register_schedules(huey):",
        '    """Apply z4j-managed schedules to a Huey instance."""',
    ]
    if not schedules:
        lines.append("    return  # no z4j schedules to migrate")
        return "\n".join(lines) + "\n"

    rendered_any = False
    for sched in schedules:
        rendered = _render_one(sched)
        if rendered:
            lines.extend(rendered)
            rendered_any = True

    if not rendered_any:
        lines.append("    return  # no z4j schedules eligible for huey export")

    return "\n".join(lines) + "\n"


def _render_one(sched: ExportedSchedule) -> list[str]:
    safe_name = re.sub(r"[\r\n\x00]+", " ", sched.name)[:200]
    safe_task_name = re.sub(r"[\r\n\x00]+", " ", sched.task_name)[:200]
    safe_expr = re.sub(r"[\r\n\x00]+", " ", sched.expression)[:200]

    if not sched.is_enabled:
        return [
            f"    # DISABLED in z4j: {safe_name} - {safe_task_name}",
            "    # @huey.periodic_task(crontab(...))",
            "",
        ]

    if sched.kind != "cron":
        return [
            f"    # {safe_name}: kind={sched.kind!r} not supported by huey;",
            f"    # keep on z4j-scheduler. expression={safe_expr!r}",
            "",
        ]

    if not _is_safe_cron_expression(sched.expression):
        return [
            f"    # {safe_name}: REFUSED cron expression {safe_expr!r}",
            "    # contains characters outside the cron field vocabulary.",
            "",
        ]

    parts = sched.expression.strip().split()
    if len(parts) == 6:
        # 6-field z4j cron has seconds; huey crontab is minute-
        # resolution. Drop the seconds field with a comment.
        parts = parts[:5]
        seconds_warning = (
            "    # NOTE: original z4j cron had seconds-precision; huey crontab is minute-only.\n"
        )
    else:
        seconds_warning = ""

    minute, hour, day, month, dow = parts
    queue_note = f"    # original queue: {json.dumps(sched.queue)}\n" if sched.queue else ""
    return [
        f"{seconds_warning}{queue_note}    # {safe_name}",
        (
            f"    @huey.periodic_task(crontab("
            f"minute={json.dumps(minute)}, "
            f"hour={json.dumps(hour)}, "
            f"day={json.dumps(day)}, "
            f"month={json.dumps(month)}, "
            f"day_of_week={json.dumps(dow)}"
            f"))"
        ),
        f"    def _z4j_{_safe_pyname(sched.name)}():",
        (f'        """Auto-registered from z4j. Calls {safe_task_name!r}."""'),
        # Operators wire the body themselves - typically calling
        # their existing task by import.
        "        from importlib import import_module",
        (f"        mod_name, _, fn_name = {json.dumps(safe_task_name)}.rpartition('.')"),
        "        getattr(import_module(mod_name), fn_name)()",
        "",
    ]


def _safe_pyname(name: str) -> str:
    """Coerce a schedule name into a valid Python identifier suffix."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)[:60] or "task"


__all__ = ["render"]
