"""Render exported schedules as a ``rq_scheduler`` Python script.

Output is a Python script the operator can drop into their app's
startup. Each schedule emits one ``scheduler.cron(...)`` /
``scheduler.schedule(...)`` / ``scheduler.enqueue_at(...)`` call.

The operator owns the ``Redis()`` connection construction - the
script doesn't hard-code one. A placeholder import is included
with a comment showing where to wire the real connection.
"""

from __future__ import annotations

import json
from collections.abc import Iterable

from z4j_scheduler.exporters._client import ExportedSchedule, py_repr


def render(schedules: Iterable[ExportedSchedule]) -> str:
    """Return a Python source string for rq-scheduler."""
    schedules = list(schedules)
    lines: list[str] = [
        "# Generated by `z4j-scheduler export --to rq`. Do not edit by hand.",
        "# Wire the Redis connection below; then call register_schedules(scheduler).",
        "",
        # Import timezone so the interval branch can emit
        # ``datetime.now(timezone.utc)`` rather than the deprecated
        # naive ``datetime.utcnow()``.
        "from datetime import datetime, timezone",
        "",
        "",
        "def register_schedules(scheduler):",
        '    """Apply z4j-managed schedules to an rq_scheduler Scheduler."""',
    ]
    if not schedules:
        lines.append("    return  # no z4j schedules to migrate")
        return "\n".join(lines) + "\n"

    for sched in schedules:
        lines.extend(_render_one(sched))
    return "\n".join(lines) + "\n"


def _render_one(sched: ExportedSchedule) -> list[str]:
    # ``py_repr`` (not json.dumps) so booleans / None inside args
    # or kwargs render as Python literals (True/False/None) rather
    # than JSON literals (true/false/null), which would NameError
    # at exec time when an operator pastes the script into their
    # startup. Same fix applied to celery + apscheduler exporters.
    args_repr = py_repr(list(sched.args))
    kwargs_repr = py_repr(dict(sched.kwargs))
    queue_kw = f", queue_name={json.dumps(sched.queue)}" if sched.queue else ""

    if not sched.is_enabled:
        # rq-scheduler has no soft-disable concept; the operator
        # comments the line out, or removes it entirely. We emit a
        # commented call so the migration is safe-by-default.
        prefix = "    # NOTE: disabled in z4j; uncomment to enable.\n    # "
    else:
        prefix = "    "

    if sched.kind == "cron":
        body = (
            f"{prefix}scheduler.cron("
            f"cron_string={json.dumps(sched.expression)}, "
            f"func={json.dumps(sched.task_name)}, "
            f"args={args_repr}, kwargs={kwargs_repr}{queue_kw})"
        )
        return [body]

    if sched.kind == "interval":
        from z4j_scheduler.exporters.celery import _interval_to_seconds

        seconds = _interval_to_seconds(sched.expression)
        # Emit a tz-aware
        # ``datetime.now(timezone.utc)`` instead of the naive
        # ``datetime.utcnow()``. RQ scheduler treats naive datetimes
        # as the host's local timezone, so an exported config
        # deployed in TZ=America/Los_Angeles ran the first interval
        # fire 7-8h late on standard time (8h on DST). Anchoring on
        # the operator's intent (UTC) keeps the first fire correct
        # regardless of where the RQ worker runs.
        body = (
            f"{prefix}scheduler.schedule("
            f"scheduled_time=datetime.now(timezone.utc), "
            f"func={json.dumps(sched.task_name)}, "
            f"args={args_repr}, kwargs={kwargs_repr}, "
            f"interval={seconds}{queue_kw})"
        )
        return [body]

    if sched.kind in ("clocked", "one_shot"):
        body = (
            f"{prefix}scheduler.enqueue_at("
            f"datetime.fromisoformat({json.dumps(sched.expression)}), "
            f"{json.dumps(sched.task_name)}, "
            f"*{args_repr}, **{kwargs_repr})"
        )
        return [body]

    return [f"    # unknown kind {sched.kind!r} for schedule {sched.name!r}"]


__all__ = ["render"]
