"""Render exported schedules as a taskiq schedule-label module.

Output is a Python module the operator imports to apply z4j-managed
schedules to their existing taskiq broker. Each schedule renders
one ``broker.task(..., schedule=[...])`` annotation::

    from .z4j_taskiq_schedules import apply_schedules

    apply_schedules(
        broker,
        by_name={
            "myapp.tasks.send_email": send_email,
        },
    )

Operators pass their actual task callables in ``by_name``; we
attach the schedule label to each one.

Supported kinds: ``cron`` → ``{"cron": "..."}``; ``one_shot`` →
``{"time": "..."}``. Interval / solar emit a comment + skip
(taskiq has no native equivalent).
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable

from z4j_scheduler.exporters._client import ExportedSchedule

_CRON_FIELD_CHARS = re.compile(r"^[\d*/,\-]+$")


def _is_safe_cron_expression(expression: str) -> bool:
    fields = expression.strip().split()
    if len(fields) not in (5, 6):
        return False
    return all(_CRON_FIELD_CHARS.match(f) for f in fields)


def render(schedules: Iterable[ExportedSchedule]) -> str:
    schedules = list(schedules)
    lines: list[str] = [
        "# Generated by `z4j-scheduler export --to taskiq`. Do not edit by hand.",
        "# Wire by importing apply_schedules and passing your broker +",
        "# the task callables you want labelled.",
        "",
        "",
        "def apply_schedules(broker, *, by_name):",
        '    """Attach z4j-managed schedule labels to existing tasks.',
        "",
        "    ``by_name`` maps schedule.task_name -> registered taskiq",
        "    task object. Tasks not in the map are skipped (logged via",
        "    print so the operator notices missing wiring).",
        '    """',
    ]
    if not schedules:
        lines.append("    return  # no z4j schedules to migrate")
        return "\n".join(lines) + "\n"

    rendered_any = False
    for sched in schedules:
        rendered = _render_one(sched)
        if rendered:
            lines.extend(rendered)
            rendered_any = True

    if not rendered_any:
        lines.append("    return  # no z4j schedules eligible for taskiq export")

    return "\n".join(lines) + "\n"


def _render_one(sched: ExportedSchedule) -> list[str]:
    safe_name = re.sub(r"[\r\n\x00]+", " ", sched.name)[:200]
    safe_task_name = re.sub(r"[\r\n\x00]+", " ", sched.task_name)[:200]
    safe_expr = re.sub(r"[\r\n\x00]+", " ", sched.expression)[:200]

    if not sched.is_enabled:
        return [
            f"    # DISABLED in z4j: {safe_name} - {safe_task_name}",
            "",
        ]

    if sched.kind == "cron":
        if not _is_safe_cron_expression(sched.expression):
            return [
                f"    # {safe_name}: REFUSED cron expression {safe_expr!r}",
                "",
            ]
        # Drop seconds field if present - taskiq uses 5-field cron.
        parts = sched.expression.strip().split()
        if len(parts) == 6:
            parts = parts[:5]
        cron_str = " ".join(parts)
        label_entry = {"cron": cron_str}
    elif sched.kind in ("clocked", "one_shot"):
        label_entry = {"time": sched.expression}
    else:
        return [
            (f"    # {safe_name}: kind={sched.kind!r} not supported by taskiq label scheduler;"),
            f"    # keep on z4j-scheduler. expression={safe_expr!r}",
            "",
        ]

    if list(sched.args):
        label_entry["args"] = list(sched.args)
    if dict(sched.kwargs):
        label_entry["kwargs"] = dict(sched.kwargs)

    label_repr = json.dumps([label_entry])
    return [
        f"    # {safe_name}",
        f"    _task = by_name.get({json.dumps(safe_task_name)})",
        "    if _task is not None:",
        f"        _task.labels['schedule'] = {label_repr}",
        "    else:",
        (f"        print('z4j taskiq export: missing task ' + {json.dumps(safe_task_name)})"),
        "",
    ]


__all__ = ["render"]
