# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from z4j_scheduler.proto import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """SchedulerService is implemented by both sides depending on
    direction:

    - Brain implements every RPC below except TriggerSchedule. Scheduler is
    the gRPC client for these brain-side RPCs.

    - Scheduler implements the legacy TriggerSchedule reverse RPC. It is off
    by default and retained for a Brain predating durable schedule control.
    A current Brain dispatches operator manual fires directly.

    In practice this is two separate gRPC services on different
    ports; we declare them as one logical service here for clarity.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSchedules = channel.unary_stream(
                '/z4j.scheduler.v1.SchedulerService/ListSchedules',
                request_serializer=scheduler__pb2.ListSchedulesRequest.SerializeToString,
                response_deserializer=scheduler__pb2.Schedule.FromString,
                _registered_method=True)
        self.WatchSchedules = channel.unary_stream(
                '/z4j.scheduler.v1.SchedulerService/WatchSchedules',
                request_serializer=scheduler__pb2.WatchSchedulesRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ScheduleEvent.FromString,
                _registered_method=True)
        self.FireSchedule = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/FireSchedule',
                request_serializer=scheduler__pb2.FireScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.FireScheduleResponse.FromString,
                _registered_method=True)
        self.TriggerSchedule = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/TriggerSchedule',
                request_serializer=scheduler__pb2.TriggerScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.TriggerScheduleResponse.FromString,
                _registered_method=True)
        self.AcknowledgeFireResult = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/AcknowledgeFireResult',
                request_serializer=scheduler__pb2.AcknowledgeFireResultRequest.SerializeToString,
                response_deserializer=scheduler__pb2.AcknowledgeFireResultResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/Ping',
                request_serializer=scheduler__pb2.PingRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PingResponse.FromString,
                _registered_method=True)
        self.NegotiateSchedulerProtocol = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/NegotiateSchedulerProtocol',
                request_serializer=scheduler__pb2.NegotiateSchedulerProtocolRequest.SerializeToString,
                response_deserializer=scheduler__pb2.NegotiateSchedulerProtocolResponse.FromString,
                _registered_method=True)
        self.ListScheduleSnapshot = channel.unary_stream(
                '/z4j.scheduler.v1.SchedulerService/ListScheduleSnapshot',
                request_serializer=scheduler__pb2.ListScheduleSnapshotRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ScheduleSnapshotFrame.FromString,
                _registered_method=True)
        self.WatchSchedulesV2 = channel.unary_stream(
                '/z4j.scheduler.v1.SchedulerService/WatchSchedulesV2',
                request_serializer=scheduler__pb2.WatchSchedulesV2Request.SerializeToString,
                response_deserializer=scheduler__pb2.ScheduleWatchFrame.FromString,
                _registered_method=True)
        self.GetScheduleState = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/GetScheduleState',
                request_serializer=scheduler__pb2.GetScheduleStateRequest.SerializeToString,
                response_deserializer=scheduler__pb2.GetScheduleStateResponse.FromString,
                _registered_method=True)
        self.QuarantineSchedule = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/QuarantineSchedule',
                request_serializer=scheduler__pb2.QuarantineScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.QuarantineScheduleResponse.FromString,
                _registered_method=True)
        self.AdvanceScheduleCursor = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/AdvanceScheduleCursor',
                request_serializer=scheduler__pb2.AdvanceScheduleCursorRequest.SerializeToString,
                response_deserializer=scheduler__pb2.AdvanceScheduleCursorResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """SchedulerService is implemented by both sides depending on
    direction:

    - Brain implements every RPC below except TriggerSchedule. Scheduler is
    the gRPC client for these brain-side RPCs.

    - Scheduler implements the legacy TriggerSchedule reverse RPC. It is off
    by default and retained for a Brain predating durable schedule control.
    A current Brain dispatches operator manual fires directly.

    In practice this is two separate gRPC services on different
    ports; we declare them as one logical service here for clarity.
    """

    def ListSchedules(self, request, context):
        """Initial sync: scheduler asks brain for every schedule it
        should tick. Server-streams paginated results so the
        scheduler can begin populating its in-memory cache
        incrementally.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSchedules(self, request, context):
        """Subscribe to schedule changes. Server-streaming. PostgreSQL uses
        LISTEN/NOTIFY for this legacy stream; SQLite polls at the configured
        watch interval. Delivery latency is therefore backend-dependent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FireSchedule(self, request, context):
        """Scheduler tells brain to fire a schedule. Brain creates a
        Command row and dispatches via the existing CommandDispatcher
        through the agent's WebSocket. Returns the command_id; the
        agent's actual completion comes back via AcknowledgeFireResult.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSchedule(self, request, context):
        """Legacy operator-initiated manual-fire path from Brain to scheduler.
        Current Brain versions dispatch manual fires directly, and the
        scheduler-side server is disabled by default. Retained for wire
        compatibility with a Brain predating durable schedule control.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeFireResult(self, request, context):
        """Scheduler reports its terminal FireSchedule receipt back to Brain.
        Current cadence progress is already committed in FireSchedule; this
        receipt records history, audit and notifications. The legacy path also
        updates the schedule projection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NegotiateSchedulerProtocol(self, request, context):
        """Authenticated, exact protocol selection. A current peer must select the
        complete supported tuple; zero/partial values never imply legacy mode.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScheduleSnapshot(self, request, context):
        """Current-protocol point-in-time snapshot. The client must buffer through
        the terminal frame and validate count/digest/watermark before applying.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSchedulesV2(self, request, context):
        """Current-protocol ordered replay strictly after a committed revision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleState(self, request, context):
        """Revision-bounded per-id recovery for retained local overlays.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuarantineSchedule(self, request, context):
        """Persist a deterministic local definition quarantine by token CAS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvanceScheduleCursor(self, request, context):
        """Persist a prepared zero-dispatch catch-up cursor transition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSchedules': grpc.unary_stream_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=scheduler__pb2.ListSchedulesRequest.FromString,
                    response_serializer=scheduler__pb2.Schedule.SerializeToString,
            ),
            'WatchSchedules': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSchedules,
                    request_deserializer=scheduler__pb2.WatchSchedulesRequest.FromString,
                    response_serializer=scheduler__pb2.ScheduleEvent.SerializeToString,
            ),
            'FireSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.FireSchedule,
                    request_deserializer=scheduler__pb2.FireScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.FireScheduleResponse.SerializeToString,
            ),
            'TriggerSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSchedule,
                    request_deserializer=scheduler__pb2.TriggerScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.TriggerScheduleResponse.SerializeToString,
            ),
            'AcknowledgeFireResult': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeFireResult,
                    request_deserializer=scheduler__pb2.AcknowledgeFireResultRequest.FromString,
                    response_serializer=scheduler__pb2.AcknowledgeFireResultResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=scheduler__pb2.PingRequest.FromString,
                    response_serializer=scheduler__pb2.PingResponse.SerializeToString,
            ),
            'NegotiateSchedulerProtocol': grpc.unary_unary_rpc_method_handler(
                    servicer.NegotiateSchedulerProtocol,
                    request_deserializer=scheduler__pb2.NegotiateSchedulerProtocolRequest.FromString,
                    response_serializer=scheduler__pb2.NegotiateSchedulerProtocolResponse.SerializeToString,
            ),
            'ListScheduleSnapshot': grpc.unary_stream_rpc_method_handler(
                    servicer.ListScheduleSnapshot,
                    request_deserializer=scheduler__pb2.ListScheduleSnapshotRequest.FromString,
                    response_serializer=scheduler__pb2.ScheduleSnapshotFrame.SerializeToString,
            ),
            'WatchSchedulesV2': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSchedulesV2,
                    request_deserializer=scheduler__pb2.WatchSchedulesV2Request.FromString,
                    response_serializer=scheduler__pb2.ScheduleWatchFrame.SerializeToString,
            ),
            'GetScheduleState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleState,
                    request_deserializer=scheduler__pb2.GetScheduleStateRequest.FromString,
                    response_serializer=scheduler__pb2.GetScheduleStateResponse.SerializeToString,
            ),
            'QuarantineSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.QuarantineSchedule,
                    request_deserializer=scheduler__pb2.QuarantineScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.QuarantineScheduleResponse.SerializeToString,
            ),
            'AdvanceScheduleCursor': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceScheduleCursor,
                    request_deserializer=scheduler__pb2.AdvanceScheduleCursorRequest.FromString,
                    response_serializer=scheduler__pb2.AdvanceScheduleCursorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'z4j.scheduler.v1.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('z4j.scheduler.v1.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """SchedulerService is implemented by both sides depending on
    direction:

    - Brain implements every RPC below except TriggerSchedule. Scheduler is
    the gRPC client for these brain-side RPCs.

    - Scheduler implements the legacy TriggerSchedule reverse RPC. It is off
    by default and retained for a Brain predating durable schedule control.
    A current Brain dispatches operator manual fires directly.

    In practice this is two separate gRPC services on different
    ports; we declare them as one logical service here for clarity.
    """

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/ListSchedules',
            scheduler__pb2.ListSchedulesRequest.SerializeToString,
            scheduler__pb2.Schedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/WatchSchedules',
            scheduler__pb2.WatchSchedulesRequest.SerializeToString,
            scheduler__pb2.ScheduleEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FireSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/FireSchedule',
            scheduler__pb2.FireScheduleRequest.SerializeToString,
            scheduler__pb2.FireScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/TriggerSchedule',
            scheduler__pb2.TriggerScheduleRequest.SerializeToString,
            scheduler__pb2.TriggerScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeFireResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/AcknowledgeFireResult',
            scheduler__pb2.AcknowledgeFireResultRequest.SerializeToString,
            scheduler__pb2.AcknowledgeFireResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/Ping',
            scheduler__pb2.PingRequest.SerializeToString,
            scheduler__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NegotiateSchedulerProtocol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/NegotiateSchedulerProtocol',
            scheduler__pb2.NegotiateSchedulerProtocolRequest.SerializeToString,
            scheduler__pb2.NegotiateSchedulerProtocolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScheduleSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/ListScheduleSnapshot',
            scheduler__pb2.ListScheduleSnapshotRequest.SerializeToString,
            scheduler__pb2.ScheduleSnapshotFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSchedulesV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/WatchSchedulesV2',
            scheduler__pb2.WatchSchedulesV2Request.SerializeToString,
            scheduler__pb2.ScheduleWatchFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/GetScheduleState',
            scheduler__pb2.GetScheduleStateRequest.SerializeToString,
            scheduler__pb2.GetScheduleStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuarantineSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/QuarantineSchedule',
            scheduler__pb2.QuarantineScheduleRequest.SerializeToString,
            scheduler__pb2.QuarantineScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvanceScheduleCursor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/AdvanceScheduleCursor',
            scheduler__pb2.AdvanceScheduleCursorRequest.SerializeToString,
            scheduler__pb2.AdvanceScheduleCursorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
