# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from z4j_scheduler.proto import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """SchedulerService is implemented by both sides depending on
    direction:
    
    - Brain implements: ListSchedules, WatchSchedules, FireSchedule,
    AcknowledgeFireResult, Ping. Scheduler is the gRPC client for
    these.
    
    - Scheduler implements: TriggerSchedule (operator-initiated
    manual fires originating from the dashboard). Brain is the
    gRPC client for this one.
    
    In practice this is two separate gRPC services on different
    ports; we declare them as one logical service here for clarity.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSchedules = channel.unary_stream(
                '/z4j.scheduler.v1.SchedulerService/ListSchedules',
                request_serializer=scheduler__pb2.ListSchedulesRequest.SerializeToString,
                response_deserializer=scheduler__pb2.Schedule.FromString,
                _registered_method=True)
        self.WatchSchedules = channel.unary_stream(
                '/z4j.scheduler.v1.SchedulerService/WatchSchedules',
                request_serializer=scheduler__pb2.WatchSchedulesRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ScheduleEvent.FromString,
                _registered_method=True)
        self.FireSchedule = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/FireSchedule',
                request_serializer=scheduler__pb2.FireScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.FireScheduleResponse.FromString,
                _registered_method=True)
        self.TriggerSchedule = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/TriggerSchedule',
                request_serializer=scheduler__pb2.TriggerScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.TriggerScheduleResponse.FromString,
                _registered_method=True)
        self.AcknowledgeFireResult = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/AcknowledgeFireResult',
                request_serializer=scheduler__pb2.AcknowledgeFireResultRequest.SerializeToString,
                response_deserializer=scheduler__pb2.AcknowledgeFireResultResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/z4j.scheduler.v1.SchedulerService/Ping',
                request_serializer=scheduler__pb2.PingRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PingResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """SchedulerService is implemented by both sides depending on
    direction:
    
    - Brain implements: ListSchedules, WatchSchedules, FireSchedule,
    AcknowledgeFireResult, Ping. Scheduler is the gRPC client for
    these.
    
    - Scheduler implements: TriggerSchedule (operator-initiated
    manual fires originating from the dashboard). Brain is the
    gRPC client for this one.
    
    In practice this is two separate gRPC services on different
    ports; we declare them as one logical service here for clarity.
    """

    def ListSchedules(self, request, context):
        """Initial sync: scheduler asks brain for every schedule it
        should tick. Server-streams paginated results so the
        scheduler can begin populating its in-memory cache
        incrementally.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSchedules(self, request, context):
        """Subscribe to schedule changes. Server-streaming. Brain pushes
        events on every create/update/delete so the scheduler updates
        its in-memory tick wheel within 100ms.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FireSchedule(self, request, context):
        """Scheduler tells brain to fire a schedule. Brain creates a
        Command row and dispatches via the existing CommandDispatcher
        through the agent's WebSocket. Returns the command_id; the
        agent's actual completion comes back via AcknowledgeFireResult.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSchedule(self, request, context):
        """Operator-initiated manual fire. Same wire effect as
        FireSchedule but tagged differently in the audit log so the
        operator-clicked vs schedule-tick distinction is preserved.
        Brain calls scheduler (reverse direction).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeFireResult(self, request, context):
        """Brain calls back when the agent has acknowledged + executed
        the fire. Scheduler updates last_run_at + computes next_run_at
        for the schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSchedules': grpc.unary_stream_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=scheduler__pb2.ListSchedulesRequest.FromString,
                    response_serializer=scheduler__pb2.Schedule.SerializeToString,
            ),
            'WatchSchedules': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSchedules,
                    request_deserializer=scheduler__pb2.WatchSchedulesRequest.FromString,
                    response_serializer=scheduler__pb2.ScheduleEvent.SerializeToString,
            ),
            'FireSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.FireSchedule,
                    request_deserializer=scheduler__pb2.FireScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.FireScheduleResponse.SerializeToString,
            ),
            'TriggerSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSchedule,
                    request_deserializer=scheduler__pb2.TriggerScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.TriggerScheduleResponse.SerializeToString,
            ),
            'AcknowledgeFireResult': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeFireResult,
                    request_deserializer=scheduler__pb2.AcknowledgeFireResultRequest.FromString,
                    response_serializer=scheduler__pb2.AcknowledgeFireResultResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=scheduler__pb2.PingRequest.FromString,
                    response_serializer=scheduler__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'z4j.scheduler.v1.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('z4j.scheduler.v1.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """SchedulerService is implemented by both sides depending on
    direction:
    
    - Brain implements: ListSchedules, WatchSchedules, FireSchedule,
    AcknowledgeFireResult, Ping. Scheduler is the gRPC client for
    these.
    
    - Scheduler implements: TriggerSchedule (operator-initiated
    manual fires originating from the dashboard). Brain is the
    gRPC client for this one.
    
    In practice this is two separate gRPC services on different
    ports; we declare them as one logical service here for clarity.
    """

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/ListSchedules',
            scheduler__pb2.ListSchedulesRequest.SerializeToString,
            scheduler__pb2.Schedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/WatchSchedules',
            scheduler__pb2.WatchSchedulesRequest.SerializeToString,
            scheduler__pb2.ScheduleEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FireSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/FireSchedule',
            scheduler__pb2.FireScheduleRequest.SerializeToString,
            scheduler__pb2.FireScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/TriggerSchedule',
            scheduler__pb2.TriggerScheduleRequest.SerializeToString,
            scheduler__pb2.TriggerScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeFireResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/AcknowledgeFireResult',
            scheduler__pb2.AcknowledgeFireResultRequest.SerializeToString,
            scheduler__pb2.AcknowledgeFireResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z4j.scheduler.v1.SchedulerService/Ping',
            scheduler__pb2.PingRequest.SerializeToString,
            scheduler__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
